sudo: required
language: python
script:
  - python setup.py install
  - pytest -vs tests/unit

before_install:
  - sudo apt-get install -y bedtools gzip
  - pip install pandas synapseclient pycrypto

matrix:
  include:
    - os: linux
      python: 3.5.3
    - os: linux
      python: 3.6.2
    - os: linux
      python: 3.7.2
