sudo: required
language: python
python:
  - "3.6"
  - "3.7"
script:
  - python setup.py install
  - pytest -vs tests

before_install:
  - sudo apt-get install -y bedtools
  - pip install pandas synapseclient pycrypto
