FROM ubuntu:bionic

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu bionic-cran35/" | tee -a /etc/apt/sources.list
RUN gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
RUN gpg -a --export E084DAB9 | apt-key add -
# GENIE dependencies
RUN apt-get update && apt-get install -y \
	git \
	r-base-core \
	r-base-dev \
	python3 \
	python3-pip \
	bedtools \ 
	dos2unix \
	g++ \
	gcc 
# VCF2MAF dependencies
RUN apt-get install -y \
	build-essential \
	cpanminus \
	curl \
	wget \
	unzip \
	automake \
	samtools \
	tabix 

RUN apt install -y \
	libmysqlclient-dev \
	libncurses5-dev \
	zlib1g-dev \
	libgsl0-dev \
	libexpat1-dev \
	libgd-dev

RUN pip3 install --upgrade pip
RUN pip install synapseclient httplib2 pycrypto PyYAML
RUN pip install pandas numexpr --upgrade

RUN rm /usr/bin/python 
RUN ln -s /usr/bin/python3 /usr/bin/python 

RUN cpanm --notest LWP::Simple DBI DBD::mysql Archive::Zip Archive::Extract HTTP::Tiny Test::Simple
RUN cpanm --notest File::Copy::Recursive Perl::OSType Module::Metadata version TAP::Harness CGI Encode
RUN cpanm --notest CPAN::Meta JSON DBD::SQLite Set::IntervalTree Archive::Tar Time::HiRes Module::Build
RUN cpanm --notest Bio::Root::Version

WORKDIR /root
RUN wget https://github.com/mskcc/vcf2maf/archive/v1.6.17.zip
RUN unzip v1.6.17.zip

WORKDIR /root/Genie
COPY ./ ./
RUN python3 setup.py sdist
RUN python3 setup.py develop

WORKDIR /root
# Must move this git clone to after the install of Genie,
# because must update cbioportal
RUN git clone https://github.com/cBioPortal/cbioportal.git

WORKDIR /root/Genie/genie
