install.packages("synapser", repos=c("https://sage-bionetworks.github.io/ran", "http://cran.fhcrc.org"))
install.packages("dplyr", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("argparse", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("rmarkdown", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("UpSetR", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("testthat", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("xtable", repo="https://ftp.osuosl.org/pub/cran/")
install.packages("ggpubr", repo="https://ftp.osuosl.org/pub/cran/")

install.packages("BiocManager", repo="https://ftp.osuosl.org/pub/cran/")
BiocManager::install("VariantAnnotation")

library(synapser)
library(dplyr)
library(argparse)
library(UpSetR)
library(rmarkdown)
library(testthat)
library(VariantAnnotation)
library(xtable)
library(ggpubr)
