source("renv/activate.R")
renv::restore()
library(synapser)
library(dplyr)
library(argparse)
library(rmarkdown)
library(testthat)
library(VariantAnnotation)
library(xtable)
library(ggpubr)
library(reticulate)
reticulate::py_install(c("pandas>=1.5,<=2.0.3", "numpy<=1.24.4"))
